#!/usr/bin/env python3
"""
Generate Player action function tables for network sync.
Parses z_player.c to extract all Player_Action_* and Player_UpperAction_* functions.

Usage: python3 generate_player_sync.py > PlayerActionFuncs.inc
"""

import os
import re
import sys
from pathlib import Path

# Paths
SCRIPT_DIR = Path(__file__).parent
BASE_DIR = SCRIPT_DIR.parent.parent.parent.parent  # soh/soh/Network/Anchor/tools -> soh
PLAYER_SOURCE = BASE_DIR / "src" / "overlays" / "actors" / "ovl_player_actor" / "z_player.c"

def find_action_funcs(content: str) -> tuple[list[str], list[str]]:
    """Find all Player_Action_* and Player_UpperAction_* function definitions"""

    # Pattern for function definitions
    # void Player_Action_Idle(Player* this, PlayState* play) {
    action_pattern = re.compile(r'^void (Player_Action_\w+)\s*\(\s*Player\s*\*', re.MULTILINE)
    # s32 Player_UpperAction_CarryActor(Player* this, PlayState* play) {
    upper_pattern = re.compile(r'^s32 (Player_UpperAction_\w+|func_80834B5C)\s*\(\s*Player\s*\*', re.MULTILINE)

    action_funcs = []
    upper_action_funcs = []

    for match in action_pattern.finditer(content):
        func_name = match.group(1)
        if func_name not in action_funcs:
            action_funcs.append(func_name)

    for match in upper_pattern.finditer(content):
        func_name = match.group(1)
        if func_name not in upper_action_funcs:
            upper_action_funcs.append(func_name)

    return action_funcs, upper_action_funcs

def generate_c_code(action_funcs: list[str], upper_action_funcs: list[str]) -> str:
    """Generate C code for Player action function tables"""
    lines = []
    lines.append("// Auto-generated by generate_player_sync.py")
    lines.append("// DO NOT EDIT MANUALLY - regenerate with:")
    lines.append("//   python3 soh/soh/Network/Anchor/tools/generate_player_sync.py > soh/soh/Network/Anchor/PlayerActionFuncs.inc")
    lines.append("//")
    lines.append(f"// {len(action_funcs)} Player_Action_* functions")
    lines.append(f"// {len(upper_action_funcs)} Player_UpperAction_* functions")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("extern \"C\" {")
    lines.append("#include \"z64player.h\"")
    lines.append("")

    # Forward declarations for action functions
    lines.append("// Forward declarations for Player action functions")
    for func in action_funcs:
        lines.append(f"void {func}(Player*, struct PlayState*);")
    lines.append("")

    # Forward declarations for upper action functions
    lines.append("// Forward declarations for Player upper action functions")
    for func in upper_action_funcs:
        lines.append(f"s32 {func}(Player*, struct PlayState*);")
    lines.append("")
    lines.append("}  // extern \"C\"")
    lines.append("")

    # Action function table
    lines.append("// Player_Action_* function table")
    lines.append(f"static PlayerActionFunc sPlayerActionFuncs[] = {{")
    for i, func in enumerate(action_funcs):
        lines.append(f"    {func},  // {i}")
    lines.append("};")
    lines.append(f"static const int sPlayerActionFuncCount = {len(action_funcs)};")
    lines.append("")

    # Upper action function table
    lines.append("// Player_UpperAction_* function table")
    lines.append(f"static UpperActionFunc sPlayerUpperActionFuncs[] = {{")
    for i, func in enumerate(upper_action_funcs):
        lines.append(f"    {func},  // {i}")
    lines.append("};")
    lines.append(f"static const int sPlayerUpperActionFuncCount = {len(upper_action_funcs)};")
    lines.append("")

    # Lookup functions
    lines.append("// Get index of an action function (-1 if not found)")
    lines.append("static s16 GetPlayerActionFuncIndex(PlayerActionFunc func) {")
    lines.append("    for (int i = 0; i < sPlayerActionFuncCount; i++) {")
    lines.append("        if (sPlayerActionFuncs[i] == func) return i;")
    lines.append("    }")
    lines.append("    return -1;")
    lines.append("}")
    lines.append("")

    lines.append("static PlayerActionFunc GetPlayerActionFuncByIndex(s16 index) {")
    lines.append("    if (index >= 0 && index < sPlayerActionFuncCount) {")
    lines.append("        return sPlayerActionFuncs[index];")
    lines.append("    }")
    lines.append("    return NULL;")
    lines.append("}")
    lines.append("")

    lines.append("// Get index of an upper action function (-1 if not found)")
    lines.append("static s8 GetPlayerUpperActionFuncIndex(UpperActionFunc func) {")
    lines.append("    for (int i = 0; i < sPlayerUpperActionFuncCount; i++) {")
    lines.append("        if (sPlayerUpperActionFuncs[i] == func) return i;")
    lines.append("    }")
    lines.append("    return -1;")
    lines.append("}")
    lines.append("")

    lines.append("static UpperActionFunc GetPlayerUpperActionFuncByIndex(s8 index) {")
    lines.append("    if (index >= 0 && index < sPlayerUpperActionFuncCount) {")
    lines.append("        return sPlayerUpperActionFuncs[index];")
    lines.append("    }")
    lines.append("    return NULL;")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)

def main():
    if not PLAYER_SOURCE.exists():
        print(f"Error: Player source not found: {PLAYER_SOURCE}", file=sys.stderr)
        sys.exit(1)

    print(f"Parsing: {PLAYER_SOURCE}", file=sys.stderr)
    content = PLAYER_SOURCE.read_text()

    action_funcs, upper_action_funcs = find_action_funcs(content)

    print(f"Found {len(action_funcs)} Player_Action_* functions", file=sys.stderr)
    print(f"Found {len(upper_action_funcs)} Player_UpperAction_* functions", file=sys.stderr)

    # Print to stdout
    print(generate_c_code(action_funcs, upper_action_funcs))

if __name__ == "__main__":
    main()
